function tr(s) {
    return WinJS.Resources.getString(s).value;
}

var greekAlphabetSymbols = {
    title: "greekAlphabetSymbols",
    data: [
//希腊字母（小写）
{ s: tr("Greek Alphabet"), pos: 0 },
{ s: "\\alpha ", pos: 0 },
{ s: "\\beta ", pos: 0 },
{ s: "\\gamma ", pos: 0 },
{ s: "\\delta ", pos: 0 },
{ s: "o ", pos: 0 },
{ s: "\\eta ", pos: 0 },
{ s: "\\zeta ", pos: 0 },
{ s: "\\varepsilon ", pos: 0 },
{ s: "\\theta ", pos: 0 },
{ s: "\\vartheta ", pos: 0 },
{ s: "\\iota ", pos: 0 },
{ s: "\\tau ", pos: 0 },
{ s: "\\nu ", pos: 0 },
{ s: "\\mu ", pos: 0 },
{ s: "\\lambda ", pos: 0 },
{ s: "\\upsilon ", pos: 0 },
{ s: "\\epsilon ", pos: 0 },
{ s: "\\varrho ", pos: 0 },
{ s: "\\varpi ", pos: 0 },
{ s: "\\rho ", pos: 0 },
{ s: "\\pi ", pos: 0 },
{ s: "\\sigma ", pos: 0 },
{ s: "\\varsigma ", pos: 0 },
{ s: "\\kappa ", pos: 0 },
{ s: "\\xi ", pos: 0 },
{ s: "\\phi ", pos: 0 },
{ s: "\\psi ", pos: 0 },
{ s: "\\chi ", pos: 0 },
{ s: "\\varphi ", pos: 0 },
{ s: "\\omega ", pos: 0 },
//希腊字符（大写）
{ s: "\\Gamma ", pos: 0 },
{ s: "\\Delta ", pos: 0 },
{ s: "A ", pos: 0 },
{ s: "B ", pos: 0 },
{ s: "E ", pos: 0 },
{ s: "Z ", pos: 0 },
{ s: "H ", pos: 0 },
{ s: "\\Theta ", pos: 0 },
{ s: "\\Lambda ", pos: 0 },
{ s: "K ", pos: 0 },
{ s: "I ", pos: 0 },
{ s: "M ", pos: 0 },
{ s: "N ", pos: 0 },
{ s: "\\Xi ", pos: 0 },
{ s: "\\Upsilon ", pos: 0 },
{ s: "\\Sigma ", pos: 0 },
{ s: "P ", pos: 0 },
{ s: "\\Pi ", pos: 0 },
{ s: "T ", pos: 0 },
{ s: "O ", pos: 0 },
{ s: "\\Phi ", pos: 0 },
{ s: "\\Psi ", pos: 0 },
{ s: "\\Omega ", pos: 0 }
    ]
};

var expansionSymbols = {
    title: "expansionSymbols",
    data: [
//常见latex扩充文字字符
{ s: tr("Expanded Characters"), pos: 0 },
{ s: "\\$ ", pos: 0 },
{ s: "\\& ", pos: 0 },
{ s: "\\% ", pos: 0 },
{ s: "\\# ", pos: 0 },
{ s: "\\backslash ", pos: 0 },
{ s: "\\^{a} ", pos: 2 },
{ s: "\\_a ", pos: 0 },
{ s: "\\~{a} ", pos: 2 },
{ s: "\\’{o} ", pos: 2 },
{ s: "\\”{o} ", pos: 2 },
{ s: "\\.{o} ", pos: 2 },
{ s: "\\H{o} ", pos: 2 },
{ s: "\\d{o} ", pos: 2 },
{ s: "\\’{o} ", pos: 2 },
{ s: "\\~{o} ", pos: 2 },
{ s: "\\u{o} ", pos: 2 },
{ s: "\\t{oo} ", pos: 2 },
{ s: "\\\b{o} ", pos: 2 },
{ s: "\\^{o} ", pos: 2 },
{ s: "\\={o} ", pos: 2 },
{ s: "\\v{o} ", pos: 2 },
{ s: "\\c{o} ", pos: 2 },
{ s: "\\P ", pos: 0 },
{ s: "\\S ", pos: 0 },
{ s: "\\dag ", pos: 0 },
{ s: "\\ddag ", pos: 0 },
{ s: "\\pounds ", pos: 0 },
{ s: "\\copyright ", pos: 0 },
{ s: "\\aa ", pos: 0 },
{ s: "\\AA ", pos: 0 },
{ s: "\\l ", pos: 0 },
{ s: "\\L ", pos: 0 },
{ s: "\\oe ", pos: 0 },
{ s: "\\ss ", pos: 0 },
{ s: "\\o ", pos: 0 },
{ s: "\\O ", pos: 0 },
{ s: "\\OE ", pos: 0 },
{ s: "\\ae ", pos: 0 },
{ s: "\\AE ", pos: 0 }
    ]
};

var accent = {
    title: "accent",
    data: [
//重音集
{ s: tr("Accents Set"), pos: 2 },
{ s: "\\hat{a} ", pos: 2 },
{ s: "\\acute{a} ", pos: 2 },
{ s: "\\bar{a} ", pos: 2 },
{ s: "\\check{a} ", pos: 2 },
{ s: "\\grave{a} ", pos: 2 },
{ s: "\\vec{a} ", pos: 2 },
{ s: "\\breve{a} ", pos: 2 },
{ s: "\\tilde{a} ", pos: 2 },
{ s: "\\dot{a} ", pos: 2 },
{ s: "\\ddot{a} ", pos: 2 }
    ]
};

var boundariesSymbol = {
    title: "boundariesSymbol",
    data: [
//界限字符
{ s: tr("Boundary Characters"), pos: 0 },
{ s: "\\uparrow ", pos: 0 },
{ s: "\\Uparrow ", pos: 0 },
{ s: "( ", pos: 0 },
{ s: ") ", pos: 2 },
{ s: "[ ", pos: 0 },
{ s: "] ", pos: 2 },
{ s: "\\updownarrow ", pos: 0 },
{ s: "\\downarrow ", pos: 0 },
{ s: "\\{ ", pos: 0 },
{ s: "\\} ", pos: 2 },
{ s: "\\lfloor ", pos: 0 },
{ s: "\\rfloor ", pos: 0 },
{ s: "\\Updownarrow ", pos: 0 },
{ s: "\\Downarrow ", pos: 0 },
{ s: "\\lceil ", pos: 0 },
{ s: "\\rceil ", pos: 0 },
{ s: "/ ", pos: 0 },
{ s: "| ", pos: 0 },
{ s: "\\backslash ", pos: 0 },
{ s: "\\rangle ", pos: 0 },
{ s: "\\langle ", pos: 0 },
{ s: "\\| ", pos: 0 }
    ]
};

var extendSymbols = {
    title: "extendSymbols",
    data: [
//可变大小数字符号
{ s: tr("Variable-sized Characters"), pos: 0 },
{ s: "\\sum ", pos: 0 },
{ s: "\\prod ", pos: 0 },
{ s: "\\coprod ", pos: 0 },
{ s: "\\int ", pos: 0 },
{ s: "\\oint ", pos: 0 },
{ s: "\\bigcap ", pos: 0 },
{ s: "\\bigcup ", pos: 0 },
{ s: "\\bigsqcup ", pos: 0 },
{ s: "\\bigvee ", pos: 0 },
{ s: "\\bigwedge ", pos: 0 },
{ s: "\\bigodot ", pos: 0 },
{ s: "\\bigotimes ", pos: 0 },
{ s: "\\bigoplus ", pos: 0 },
{ s: "\\biguplus ", pos: 0 }
    ]
};

var notSymbols = {
    title: "notSymbols",
    data: [
//否定关系符
{ s: tr("Negative-relationship Characters"), pos: 0 },
{ s: "\\not\\sqsubseteq ", pos: 0 },
{ s: "\\not\\preceq ", pos: 0 },
{ s: "\\not\\asymp ", pos: 0 },
{ s: "\\not< ", pos: 0 },
{ s: "\\not\\leq ", pos: 0 },
{ s: "\\not\\prec ", pos: 0 },
{ s: "\\not\\sqsupseteq ", pos: 0 },
{ s: "\\not\\succeq ", pos: 0 },
{ s: "\\not\\equiv ", pos: 0 },
{ s: "\\not> ", pos: 0 },
{ s: "\\not\\geq ", pos: 0 },
{ s: "\\not\\succ ", pos: 0 },
{ s: "\\not\\subseteq ", pos: 0 },
{ s: "\\not\\supset ", pos: 0 },
{ s: "\\not\\simeq ", pos: 0 },
{ s: "\\not= ", pos: 0 },
{ s: "\\not\\sim ", pos: 0 },
{ s: "\\not\\cong ", pos: 0 },
{ s: "\\not\\supseteq ", pos: 0 },
{ s: "\\not\\subset ", pos: 0 },
{ s: "\\not\\approx ", pos: 0 }
    ]
};


var relationshipSymbols = {
    title: "relationshipSymbols",
    data: [
//关系符
{ s: tr("Other Relationship Characters"), pos: 0 },
{ s: "\\leq ", pos: 0 },
{ s: "\\prec ", pos: 0 },
{ s: "\\preceq ", pos: 0 },
{ s: "\\ll ", pos: 0 },
{ s: "\\subset ", pos: 0 },
{ s: "\\subseteq ", pos: 0 },
{ s: "\\sqsubset ", pos: 0 },
{ s: "\\sim ", pos: 0 },
{ s: "\\in ", pos: 0 },
{ s: "\\vdash ", pos: 0 },
{ s: "\\geq ", pos: 0 },
{ s: "\\succ ", pos: 0 },
{ s: "\\succeq ", pos: 0 },
{ s: "\\equiv ", pos: 0 },
{ s: "\\supset ", pos: 0 },
{ s: "\\supseteq ", pos: 0 },
{ s: "\\frown ", pos: 0 },
{ s: "\\smile ", pos: 0 },
{ s: "\\ni ", pos: 0 },
{ s: "\\dashv ", pos: 0 },
{ s: "\\gg ", pos: 0 },
{ s: "\\sqsubseteq ", pos: 0 },
{ s: "\\cong ", pos: 0 },
{ s: "\\asymp ", pos: 0 },
{ s: "\\approx ", pos: 0 },
{ s: "\\simeq ", pos: 0 },
{ s: "\\neq ", pos: 0 },
{ s: "\\doteq ", pos: 0 },
{ s: "\\propto ", pos: 0 },
{ s: "\\models ", pos: 0 },
{ s: "\\perp ", pos: 0 },
{ s: "\\mid ", pos: 0 },
{ s: "\\parallel ", pos: 0 },
{ s: "\\bowtie ", pos: 0 },
{ s: "\\Join ", pos: 0 },
{ s: "\\because ", pos: 0 },
{ s: "\\therefore ", pos: 0 },
{ s: "\\measuredangle ", pos: 0 },
{ s: "\\sphericalangle ", pos: 0 },
{ s: "\\Re ", pos: 0 },
{ s: "\\varnothing ", pos: 0 },
{ s: "\\infty ", pos: 0 },
{ s: "\\mho ", pos: 0 },
{ s: "\\wp ", pos: 0 },
{ s: "\\SS ", pos: 0 },
{ s: "\\cent ", pos: 0 },
{ s: "\\euro ", pos: 0 },
{ s: "\\sqsupseteq ", pos: 0 },
{ s: "\\nsubseteq ", pos: 0 },
{ s: "\\nsupseteq ", pos: 0 },
{ s: "\\subseteqq ", pos: 0 },
{ s: "\\supseteqq ", pos: 0 },
{ s: "\\nsupseteqq ", pos: 0 },
{ s: "\\notin ", pos: 0 },
{ s: "\\leftrightharpoons ", pos: 0 },
{ s: "\\rightleftharpoons ", pos: 0 },
{ s: "\\angle ", pos: 0 }
    ]
};

var doubleSymbols = {
    title: "doubleSymbols",
    data: [
//双运算符
{ s: tr("Double Characters"), pos: 0 },
{ s: "\\pm ", pos: 0 },
{ s: "\\mp ", pos: 0 },
{ s: "\\times ", pos: 0 },
{ s: "\\div ", pos: 0 },
{ s: "\\ast ", pos: 0 },
{ s: "\\star ", pos: 0 },
{ s: "\\circ ", pos: 0 },
{ s: "\\triangleleft ", pos: 0 },
{ s: "\\cdot ", pos: 0 },
{ s: "\\cap ", pos: 0 },
{ s: "\\Cap ", pos: 0 },
{ s: "\\cup ", pos: 0 },
{ s: "\\Cup ", pos: 0 },
{ s: "\\uplus ", pos: 0 },
{ s: "\\sqcap ", pos: 0 },
{ s: "\\bigtriangledown ", pos: 0 },
{ s: "\\vee ", pos: 0 },
{ s: "\\wedge ", pos: 0 },
{ s: "\\setminus ", pos: 0 },
{ s: "\\wr ", pos: 0 },
{ s: "\\diamond ", pos: 0 },
{ s: "\\bigtriangleup ", pos: 0 },
{ s: "\\sqcup ", pos: 0 },
{ s: "\\bullet ", pos: 0 },
{ s: "\\ddagger ", pos: 0 },
{ s: "\\amalg ", pos: 0 },
{ s: "\\triangleright ", pos: 0 },
{ s: "\\bigcirc ", pos: 0 },
{ s: "\\oplus ", pos: 0 },
{ s: "\\ominus ", pos: 0 },
{ s: "\\otimes ", pos: 0 },
{ s: "\\dagger ", pos: 0 },
{ s: "\\oslash ", pos: 0 },
{ s: "\\odot ", pos: 0 },
{ s: "\\unrhd ", pos: 0 },
{ s: "\\rhd ", pos: 0 },
{ s: "\\unlhd ", pos: 0 },
{ s: "\\lhd ", pos: 0 }
    ]
};

var logicSymbols = {
    title: "logicSymbols",
    data: [
//数字与逻辑函数符
{ s: tr("Digital and Logic Function Characters"), pos: 0 },
{ s: "\\arccos ", pos: 0 },
{ s: "\\arcsin ", pos: 0 },
{ s: "\\arctan ", pos: 0 },
{ s: "\\arg ", pos: 0 },
{ s: "\\cos ", pos: 0 },
{ s: "\\cosh ", pos: 0 },
{ s: "\\cot ", pos: 0 },
{ s: "\\sinh ", pos: 0 },
{ s: "\\coth ", pos: 0 },
{ s: "\\csc ", pos: 0 },
{ s: "\\deg ", pos: 0 },
{ s: "\\det ", pos: 0 },
{ s: "\\dim ", pos: 0 },
{ s: "\\exp ", pos: 0 },
{ s: "\\gcd ", pos: 0 },
{ s: "\\sup ", pos: 0 },
{ s: "\\hom ", pos: 0 },
{ s: "\\inf ", pos: 0 },
{ s: "\\ker ", pos: 0 },
{ s: "\\lg ", pos: 0 },
{ s: "\\lim ", pos: 0 },
{ s: "\\liminf ", pos: 0 },
{ s: "\\limsup ", pos: 0 },
{ s: "\\tan ", pos: 0 },
{ s: "\\ln ", pos: 0 },
{ s: "\\log ", pos: 0 },
{ s: "\\max ", pos: 0 },
{ s: "\\min ", pos: 0 },
{ s: "\\Pr ", pos: 0 },
{ s: "\\sec ", pos: 0 },
{ s: "\\sin ", pos: 0 },
{ s: "\\tanh ", pos: 0 }
    ]
};

var arrowSymbols = {
    title: "arrowSymbols",
    data: [
//箭头字符和点
{ s: tr("Dots and Modified Characters"), pos: 0 },
{ s: "\\cdots ", pos: 0 },
{ s: "\\ddots ", pos: 0 },
{ s: "\\vdots ", pos: 0 },

{ s: "\\longleftrightarrow ", pos: 0 },
{ s: "\\Longleftarrow ", pos: 0 },
{ s: "\\rightarrow ", pos: 0 },
{ s: "\\leftarrow ", pos: 0 },
{ s: "\\Longleftrightarrow ", pos: 0 },
{ s: "\\longleftarrow ", pos: 0 },
{ s: "\\Rightarrow ", pos: 0 },
{ s: "\\Leftarrow ", pos: 0 },
{ s: "\\leftharpoondown ", pos: 0 },
{ s: "\\updownarrow ", pos: 0 },
{ s: "\\mapsto ", pos: 0 },
{ s: "\\uparrow ", pos: 0 },
{ s: "\\rightharpoondown ", pos: 0 },
{ s: "\\rightharpoonup ", pos: 0 },
{ s: "\\Updownarrow ", pos: 0 },
{ s: "\\Uparrow ", pos: 0 },
{ s: "\\leftrightarrow ", pos: 0 },
{ s: "\\Longrightarrow ", pos: 0 },
{ s: "\\to ", pos: 0 },
{ s: "\\searrow ", pos: 0 },
{ s: "\\Leftrightarrow ", pos: 0 },
{ s: "\\longrightarrow ", pos: 0 },
{ s: "\\nearrow ", pos: 0 },
{ s: "\\swarrow ", pos: 0 },
{ s: "\\hookrightarrow ", pos: 0 },
{ s: "\\hookleftarrow ", pos: 0 },
{ s: "\\longmapsto ", pos: 0 },
{ s: "\\nwarrow ", pos: 0 },

{ s: "{a}' ", pos: 3 },
{ s: "{a}'' ", pos: 4 },
{ s: "\\not{a} ", pos: 2 },
{ s: "\\widetilde{a} ", pos: 2 },
{ s: "\\widehat{a} ", pos: 2 },
{ s: "\\overleftarrow{a} ", pos: 2 },
{ s: "\\overrightarrow{a} ", pos: 2 },
{ s: "\\overline{a} ", pos: 2 },
{ s: "\\underline{a} ", pos: 2 },
{ s: "\\overbrace{a} ", pos: 2 },
{ s: "\\underbrace{a} ", pos: 2 },
{ s: "\\xleftarrow[]{a} ", pos: 5 },
{ s: "\\xrightarrow[]{a} ", pos: 5 },
{ s: "\\overset{a}{\\leftarrow} ", pos: 14 },
{ s: "\\overset{a}{\\rightarrow} ", pos: 15 },
{ s: "\\underset{a}{\\leftarrow} ", pos: 14 },
{ s: "\\underset{a}{\\rightarrow} ", pos: 15 },
{ s: "C_{a}^{b} ", pos: 6 },
{ s: "\\sqrt{a} ", pos: 2 },
{ s: "\\tfrac{a}{b} ", pos: 5 },
{ s: "\\frac{a}{b} ", pos: 5 },
{ s: "\\frac{\\partial }{\\partial x} ", pos: 14 }
    ]
};

var choasSymbols = {
    title: "choasSymbols",
    data: [
//各种混合杂字符
{ s: tr("Other Characters"), pos: 0 },
{ s: "\\aleph ", pos: 0 },
{ s: "\\hbar ", pos: 0 },
{ s: "\\imath ", pos: 0 },
{ s: "\\jmath ", pos: 0 },
{ s: "\\ell ", pos: 0 },
{ s: "\\wp ", pos: 0 },
{ s: "\\emptyset ", pos: 0 },
{ s: "\\natural ", pos: 0 },
{ s: "\\mho ", pos: 0 },
{ s: "\\prime ", pos: 0 },
{ s: "\\Re ", pos: 0 },
{ s: "\\Im ", pos: 0 },
{ s: "\\Diamond ", pos: 0 },
{ s: "\\forall ", pos: 0 },
{ s: "\\triangle ", pos: 0 },
{ s: "\\| ", pos: 0 },
{ s: "\\angle ", pos: 0 },
{ s: "\\flat ", pos: 0 },
{ s: "\\spadesuit ", pos: 0 },
{ s: "\\backslash ", pos: 0 },
{ s: "\\top ", pos: 0 },
{ s: "\\nabla ", pos: 0 },
{ s: "\\infty ", pos: 0 },
{ s: "\\neg ", pos: 0 },
{ s: "\\partial ", pos: 0 },
{ s: "\\sharp ", pos: 0 },
{ s: "\\clubsuit ", pos: 0 },
{ s: "\\surd ", pos: 0 },
{ s: "\\bot ", pos: 0 },
{ s: "\\Box ", pos: 0 },
{ s: "\\diamondsuit ", pos: 0 },
{ s: "\\heartsuit ", pos: 0 },
{ s: "\\exists ", pos: 0 },

{ s: "\\mathbb{P} ", pos: 2 },
{ s: "\\mathbb{N} ", pos: 2 },
{ s: "\\mathbb{Z} ", pos: 2 },
{ s: "\\mathbb{I} ", pos: 2 },
{ s: "\\mathbb{Q} ", pos: 2 },
{ s: "\\mathbb{R} ", pos: 2 },
{ s: "\\mathbb{C} ", pos: 2 },
{ s: "\\mathbb{N} ", pos: 2 },
{ s: "\\dotplus ", pos: 0 },
{ s: "\\lozenge ", pos: 0 },
{ s: "\\blacklozenge ", pos: 0 },
{ s: "\\bigstar ", pos: 0 },
{ s: "\\square ", pos: 0 },
{ s: "\\blacksquare ", pos: 0 },
{ s: "\\blacktriangle ", pos: 0 },
{ s: "\\triangledown ", pos: 0 },
{ s: "\\blacktriangledown ", pos: 0 },
{ s: "\\circledcirc ", pos: 0 },
{ s: "\\circledast ", pos: 0 },
{ s: "\\circleddash ", pos: 0 }
    ]
};

//var otherSymbols = {
//    title: "otherSymbols",
//    data: [
//{ s: "其    他    符    号", pos: 0 },
//
//   ]
//};